In [ ]:
#Cell 1: Imports + Importing metadata
import pandas as pd
import numpy as np

df = pd.read_csv('/content/gnps_metadata.csv')
df = df.iloc[78:]
df

,MassiveID,filename,SampleType,SampleTypeSub1,NCBITaxonomy,YearOfAnalysis,SampleCollectionMethod,SampleExtractionMethod,InternalStandardsUsed,MassSpectrometer,...,ComorbidityListDOIDIndex,SampleCollectionDateandTime,Country,HumanPopulationDensity,LatitudeandLongitude,DepthorAltitudeMeters,UniqueSubjectID,LifeStage,UBERONOntologyIndex,DOIDOntologyIndex
78,MSV000083077,PHT_20_010_Cort_1200.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_010_Cort_1200,Early Adulthood (18 yrs < x <= 45 yrs),UBERON:0001836,DOID:9970
79,MSV000083077,PHT_20_010_Cort_1600.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_010_Cort_1600,Early Adulthood (18 yrs < x <= 45 yrs),UBERON:0001836,DOID:9970
80,MSV000083077,PHT_20_010_Cort_1900.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_010_Cort_1900,Early Adulthood (18 yrs < x <= 45 yrs),UBERON:0001836,DOID:9970
81,MSV000083077,PHT_20_018_Cort_1000.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_018_Cort_1000,Early Adulthood (18 yrs < x <= 45 yrs),UBERON:0001836,no disease reported
82,MSV000083077,PHT_20_018_Cort_1600.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_018_Cort_1600,Early Adulthood (18 yrs < x <= 45 yrs),UBERON:0001836,no disease reported
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,MSV000083077,PHT_20_162_Cort_1900.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_162_Cort_1900,Early Adulthood (18 yrs < x <= 45 yrs),UBERON:0001836,DOID:9970
380,MSV000083077,PHT_20_162_Cort_Waking.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_162_Cort_Waking,Early Adulthood (18 yrs < x <= 45 yrs),UBERON:0001836,DOID:9970
381,MSV000083077,PHT_20_163_Cort_1000.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_163_Cort_1000,Middle Adulthood (45 yrs < x <= 65 yrs),UBERON:0001836,DOID:9970
382,MSV000083077,PHT_20_163_Cort_1200.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_163_Cort_1200,Middle Adulthood (45 yrs < x <= 65 yrs),UBERON:0001836,DOID:9970
383,MSV000083077,PHT_20_163_Cort_Waking.mzML,animal,biofluid,9606|Homo sapiens,2017,liquid,methanol-water (4:1),sulfamethazine;sulfadimethoxine,Q Exactive|MS:1001911,...,not applicable,not specified,United States of America,not collected,32.842;-117.258,193,MSV000083077_PHT_20_163_Cort_Waking,Middle Adulthood (45 yrs < x <= 65 yrs),UBERON:0001836,DOID:9970

In [ ]:
#Reading txt file to identify column names
file_path = "/content/11259_20230206-075538.txt"

with open(file_path, 'r') as f:
  content = f.read()
  print(f"Content of '{file_path}':\n{content}")

Content of '/content/11259_20230206-075538.txt':
sample_name	ac_nk_preex	age	age_units	anonymized_name	bdi_cognitive3	bdi_somatic3	bdi_total3	bmi	cbc_lymph_post_ex4	cbc_lymph_pre_ex4	cbc_monos_post_ex4	cbc_monos_pre_ex4	cbc_segs_post_ex4	cbc_segs_pre_ex4	cbc_wbc_post_ex4	cbc_wbc_pre_ex4	cesd_total3	collection_time	collection_timestamp	dahip3	datotalpercentfat3	datrunkpercentfat3	dawaist3	del10	del8	del9	description	dmissing_extracted	dna_extracted	ebhpkexervo2l3	ebhpkexervo2ml3	elevation	env_biome	env_feature	env_material	env_package	epi_preex	geo_loc_name	grandavedbp2	grandavesbp2	height	hlcholesterol2	hlldlcholesterol2	hltriglycerides2	hltshsensitive2	host_body_habitat	host_body_product	host_body_site	host_scientific_name	host_subject_id	host_taxid	hthdlcholesterol2	latitude	life_stage	longitude	lteq1a3	lteq1b3	lteq1c3	mc_totalscore3	mfsi_emotiomissingl3	mfsi_emotional3	mfsi_general3	mfsi_mental3	mfsi_physical3	mfsi_total3	mfsi_vigor3	ne_preex	oq_total3	physical_specimen_location	physical_specimen_remaining	poms_anger3	poms_confusion3	poms_depression3	poms_fatigue3	poms_tension3	poms_total3	poms_vigor3	postex_14dim16p	postex_14p16n	postex_14p16p	preex_14dim16p	preex_14p16n	preex_14p16p	pss10_totalscore3	qiita_bdi_quarters	qiita_bdi_total_category	qiita_bmi_category	qiita_del8_category	qiita_study_id	race	risk_cvd_10y_bmi	risk_cvd_10y_bmi_diab	risk_cvd_10y_lip	risk_cvd_10y_lip_diab	risk_cvd_30y_bmi	risk_cvd_30y_bmi_diab	risk_cvd_30y_lip	risk_cvd_30y_lip_diab	risk_hcvd_30y_bmi	risk_hcvd_30y_bmi_diab	risk_hcvd_30y_lip	risk_hcvd_30y_lip_diab	sample_collection_time_hongcode	sample_type	scientific_name	sex	sf36_enrfat3	sf36_ewb3	sf36_genhel3	sf36_pain3	sf36_physf3	sf36_rldep3	sf36_rldph3	sf36_socfun3	sil1pre	sil6pre	stat_anxietys3	stat_anxietyt3	stnfpre	subject_id	subject_name	subject_name_hongcode	taxon_id	title	tnf_per	weight
11259.BLANK3.4A	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK3.4B	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK3.4C	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK3.4D	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK3.4E	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK3.4F	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK3.4G	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK3.4H	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK4.10A	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable
11259.BLANK4.10B	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		10/11/17	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	processing control		TRUE	not applicable	not applicable	193	urban biome	research facility	sterile water	misc environment	not applicable	USA:CA:San Diego	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	32.842	not applicable	-117.258	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	ucsdmi	FALSE	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable		not applicable	11259	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	blank	metagenome	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable	not applicable			not applicable	256318	UCSD_OMB	not applicable	not applicable

In [ ]:
#File upload
import io
from google.colab import files
uploaded = files.upload()
file_name = "11259_20230206-075538.txt"
df = pd.read_csv(io.BytesIO(uploaded[file_name]), sep='\t')

Saving 11259_20230206-075538.txt to 11259_20230206-075538.txt

In [ ]:
#Downloading metadata to colab content
output_csv_name = 'metadata.csv'
df.to_csv(output_csv_name, index=False)

In [ ]:
df

,sample_name,ac_nk_preex,age,age_units,anonymized_name,bdi_cognitive3,bdi_somatic3,bdi_total3,bmi,cbc_lymph_post_ex4,...,stat_anxietys3,stat_anxietyt3,stnfpre,subject_id,subject_name,subject_name_hongcode,taxon_id,title,tnf_per,weight
0,11259.BLANK3.4A,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,...,not applicable,not applicable,not applicable,NaN,NaN,not applicable,256318,UCSD_OMB,not applicable,not applicable
1,11259.BLANK3.4B,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,...,not applicable,not applicable,not applicable,NaN,NaN,not applicable,256318,UCSD_OMB,not applicable,not applicable
2,11259.BLANK3.4C,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,...,not applicable,not applicable,not applicable,NaN,NaN,not applicable,256318,UCSD_OMB,not applicable,not applicable
3,11259.BLANK3.4D,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,...,not applicable,not applicable,not applicable,NaN,NaN,not applicable,256318,UCSD_OMB,not applicable,not applicable
4,11259.BLANK3.4E,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,not applicable,...,not applicable,not applicable,not applicable,NaN,NaN,not applicable,256318,UCSD_OMB,not applicable,not applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,11259.PHT.20.162.Cort.1900,not collected,26,years,pht_20_162,2,0,2,28.9,50,...,31,33,2.041800278,PHT_20_162,PHT_20_162,pht_20_162,447426,UCSD_OMB,74,91.5
453,11259.PHT.20.162.Cort.Waking,not collected,26,years,pht_20_162,2,0,2,28.9,50,...,31,33,2.041800278,PHT_20_162,PHT_20_162,pht_20_162,447426,UCSD_OMB,74,91.5
454,11259.PHT.20.163.Cort.1000,not collected,55,years,pht_20_163,0,0,0,26.7,38,...,20,20,2.600226603,PHT_20_163,PHT_20_163,pht_20_163,447426,UCSD_OMB,39,55.3
455,11259.PHT.20.163.Cort.1200,not collected,55,years,pht_20_163,0,0,0,26.7,38,...,20,20,2.600226603,PHT_20_163,PHT_20_163,pht_20_163,447426,UCSD_OMB,39,55.3
456,11259.PHT.20.163.Cort.Waking,not collected,55,years,pht_20_163,0,0,0,26.7,38,...,20,20,2.600226603,PHT_20_163,PHT_20_163,pht_20_163,447426,UCSD_OMB,39,55.3

In [ ]:
files.download(output_csv_name)

In [ ]:
#Ensuring each file has a depression output
depression_values_list = df['poms_depression3'].tolist()
print(len(depression_values_list))
print(len(df))

457
457

In [ ]:
#Checking to see if this specific file is found in the df
value = "PHT_20_018_Cort_1900"
value_found = df.isin([value]).any().any()
print(f"Value '{value}' found: {value_found}")

Value 'PHT_20_018_Cort_1900' found: False

In [ ]:
#Creating a new df with depression label and sample
df_new = df[['sample_name', 'poms_depression3']]
df_new = df_new[df_new['poms_depression3'] != 'not applicable']
df_new

                      sample_name poms_depression3
134    11259.PHT.20.010.Cort.1200                3
135    11259.PHT.20.010.Cort.1600                3
136    11259.PHT.20.010.Cort.1900                3
137    11259.PHT.20.018.Cort.1000                0
138    11259.PHT.20.018.Cort.1600                0
..                            ...              ...
452    11259.PHT.20.162.Cort.1900                3
453  11259.PHT.20.162.Cort.Waking                3
454    11259.PHT.20.163.Cort.1000                0
455    11259.PHT.20.163.Cort.1200                0
456  11259.PHT.20.163.Cort.Waking                0

[323 rows x 2 columns]

In [ ]:
#Processing the datatable to look nicer
df_new['sample_name'] = df_new['sample_name'].str.replace("11259.", '', regex=False)
df_new['sample_name'] = df_new['sample_name'].str.replace(".", '_', regex=False)
df_new['sample_name'] = df_new['sample_name'].astype(str) + ".mzML"
df_new

                     sample_name poms_depression3
134    PHT_20_010_Cort_1200.mzML                3
135    PHT_20_010_Cort_1600.mzML                3
136    PHT_20_010_Cort_1900.mzML                3
137    PHT_20_018_Cort_1000.mzML                0
138    PHT_20_018_Cort_1600.mzML                0
..                           ...              ...
452    PHT_20_162_Cort_1900.mzML                3
453  PHT_20_162_Cort_Waking.mzML                3
454    PHT_20_163_Cort_1000.mzML                0
455    PHT_20_163_Cort_1200.mzML                0
456  PHT_20_163_Cort_Waking.mzML                0

[323 rows x 2 columns]

In [ ]:
#Loading depression output statistics
print(df_new['poms_depression3'].unique())
print(df_new['poms_depression3'].value_counts())

['3' '0' '6' '9' '1' '22' '2' 'not provided' '14' '5' '8' '4' '36' '27'
 '13']
poms_depression3
0               130
1                49
3                35
4                22
6                19
2                15
not provided      9
5                 9
9                 8
22                5
8                 5
13                5
36                5
27                4
14                3
Name: count, dtype: int64

In [ ]:
#Getting rid of "not provided" files
df_new = df_new[df_new['poms_depression3'] != "not provided"]
df_new

                     sample_name poms_depression3
134    PHT_20_010_Cort_1200.mzML                3
135    PHT_20_010_Cort_1600.mzML                3
136    PHT_20_010_Cort_1900.mzML                3
137    PHT_20_018_Cort_1000.mzML                0
138    PHT_20_018_Cort_1600.mzML                0
..                           ...              ...
452    PHT_20_162_Cort_1900.mzML                3
453  PHT_20_162_Cort_Waking.mzML                3
454    PHT_20_163_Cort_1000.mzML                0
455    PHT_20_163_Cort_1200.mzML                0
456  PHT_20_163_Cort_Waking.mzML                0

[314 rows x 2 columns]

In [ ]:
len(df_new)

314

In [ ]:
df_new.to_csv('new_metadata.csv', index=True)

In [ ]:
files.download("new_metadata.csv")

In [ ]:
#normalizing all depression scores

def categorize_depression(value):
  if value=="0":
    return 0
  if value=="1":
    return 1
  if value=="2":
    return 2
  if value=="3":
    return 3
  else:
    return 4

df_new['diagnosis'] = df_new['poms_depression3'].apply(categorize_depression)

print(df_new['diagnosis'].value_counts())

diagnosis
0    130
4     85
1     49
3     35
2     15
Name: count, dtype: int64

/tmp/ipython-input-832235992.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['diagnosis'] = df_new['poms_depression3'].apply(categorize_depression)

In [ ]:
df_new = df_new.rename(columns={'diagnosis': "diagnosis", "sample_name": "file_name"})
df_new

                       file_name poms_depression3  diagnosis
134    PHT_20_010_Cort_1200.mzML                3          3
135    PHT_20_010_Cort_1600.mzML                3          3
136    PHT_20_010_Cort_1900.mzML                3          3
137    PHT_20_018_Cort_1000.mzML                0          0
138    PHT_20_018_Cort_1600.mzML                0          0
..                           ...              ...        ...
452    PHT_20_162_Cort_1900.mzML                3          3
453  PHT_20_162_Cort_Waking.mzML                3          3
454    PHT_20_163_Cort_1000.mzML                0          0
455    PHT_20_163_Cort_1200.mzML                0          0
456  PHT_20_163_Cort_Waking.mzML                0          0

[314 rows x 3 columns]

In [ ]:
df_new = df_new.drop(columns=['poms_depression3'])
df_new

     index                    file_name  diagnosis
0      134    PHT_20_010_Cort_1200.mzML          3
1      135    PHT_20_010_Cort_1600.mzML          3
2      136    PHT_20_010_Cort_1900.mzML          3
3      137    PHT_20_018_Cort_1000.mzML          0
4      138    PHT_20_018_Cort_1600.mzML          0
..     ...                          ...        ...
309    452    PHT_20_162_Cort_1900.mzML          3
310    453  PHT_20_162_Cort_Waking.mzML          3
311    454    PHT_20_163_Cort_1000.mzML          0
312    455    PHT_20_163_Cort_1200.mzML          0
313    456  PHT_20_163_Cort_Waking.mzML          0

[314 rows x 3 columns]

In [ ]:
df_new['diagnosis'].value_counts()

diagnosis
0    130
4     85
1     49
3     35
2     15
Name: count, dtype: int64

In [ ]:
#saving file
df_new.to_csv("UCSD_depression_dataset.csv")
files.download("UCSD_depression_dataset.csv")